`timescale 1ns / 1ps

//==============================================================================
// G_FPGA_Top
//------------------------------------------------------------------------------
// Absolute Basys 3 top level for the periodic-signal measurement system.
//
// External resources:
//   sys_clk       : 100 MHz board oscillator, W5
//   sys_rst_n     : mapped to BtnC/U18.  Basys 3 BtnC is electrically active
//                   high, so BUTTON_ACTIVE_HIGH defaults to 1.  The port name
//                   is kept as requested; set BUTTON_ACTIVE_HIGH=0 only when
//                   an external active-low reset source is wired to this pin.
//   key_cycle     : BtnU/T18, toggles one-period/three-period HMI display mode
//   adc_clk_out   : ODDR-forwarded 4.096045 MHz clock, JB1/A14
//   adc_data_in   : AD9226 parallel bus on JB2..JB10 and JC1..JC4/JC7
//   uart_tx       : UART display TX on JA1/J1
//==============================================================================
module G_FPGA_Top #(
    parameter integer BUTTON_ACTIVE_HIGH = 1
)(
    input  wire       sys_clk,
    input  wire       sys_rst_n,
    input  wire       key_cycle,
    input  wire [11:0] adc_data_in,
    output wire       adc_clk_out,
    output wire       uart_tx
);

    wire clk_algo;
    wire clk_adc;
    wire mmcm_locked;

    // Basys 3 pushbuttons have a pull-down and assert high.  The parameter
    // keeps the wrapper usable with an active-low external reset source too.
    wire reset_button_asserted = BUTTON_ACTIVE_HIGH ? sys_rst_n : ~sys_rst_n;
    wire mmcm_reset = reset_button_asserted;
    wire reset_async = reset_button_asserted | ~mmcm_locked;

    MMCM_Top u_mmcm_top (
        .sys_clk_in(sys_clk),
        .reset     (mmcm_reset),
        .clk_algo  (clk_algo),
        .clk_adc   (clk_adc),
        .locked    (mmcm_locked)
    );

    wire rst_algo;
    wire rst_adc;

    Reset_Synchronizer u_reset_sync_algo (
        .clk (clk_algo),
        .arst(reset_async),
        .srst(rst_algo)
    );

    Reset_Synchronizer u_reset_sync_adc (
        .clk (clk_adc),
        .arst(reset_async),
        .srst(rst_adc)
    );

    // The processing subsystem is entirely in the 100 MHz algorithm domain.
    // Its ADC source-capture registers receive the separately synchronized
    // rst_adc below, preventing a reset signal generated by clk_algo from
    // being timed into the BUFR/ADC clock domain.
    wire rst_subsystem = rst_algo;

    // Forward the ADC clock through an ODDR.  D1=1 and D2=0 produce a normal
    // clock waveform while the pad is driven by the dedicated output cell.
    ODDR #(
        .DDR_CLK_EDGE("SAME_EDGE")
    ) u_adc_clock_oddr (
        .Q (adc_clk_out),
        .C (clk_adc),
        .CE(1'b1),
        .D1(1'b1),
        .D2(1'b0),
        .R (reset_async),
        .S (1'b0)
    );

    wire key_cycle_state;
    wire key_cycle_pulse;

    Button_Debounce #(
        .CLK_FREQ_HZ(100_000_000),
        .DEBOUNCE_MS(20)
    ) u_button_debounce_cycle (
        .clk         (clk_algo),
        .rst         (rst_algo),
        .button_in   (key_cycle),
        .button_state(key_cycle_state),
        .button_pulse(key_cycle_pulse)
    );

    reg display_three_cycles;
    always @(posedge clk_algo) begin
        if (rst_algo)
            display_three_cycles <= 1'b0;
        else if (key_cycle_pulse)
            display_three_cycles <= ~display_three_cycles;
    end

    // Results and debug signals from the complete measurement subsystem.
    wire [16:0] vpp_out;
    wire [15:0] vrms_out;
    wire [31:0] mean_square_out;
    wire        result_valid;
    wire        capture_busy;
    wire        calc_busy;
    wire [11:0] max_index_out;
    wire [31:0] f1_hz_out;
    wire [31:0] amp_f1_out;
    wire        peak_result_valid;
    wire        fft_result_valid;
    wire        fft_busy;
    wire        peak_busy;
    wire        hmi_busy;
    wire        waveform_done;
    wire        frame_valid;
    wire [4:0]  uart_state;

    Capture_Calc_Subsystem u_capture_calc_subsystem (
        .adc_clk             (clk_adc),
        .calc_clk            (clk_algo),
        .rst                 (rst_subsystem),
        .rst_adc             (rst_adc),
        .adc_data            (adc_data_in),
        .display_three_cycles(display_three_cycles),
        .vpp_out             (vpp_out),
        .vrms_out            (vrms_out),
        .mean_square_out     (mean_square_out),
        .result_valid        (result_valid),
        .capture_busy        (capture_busy),
        .calc_busy           (calc_busy),
        .max_index_out       (max_index_out),
        .f1_hz_out           (f1_hz_out),
        .amp_f1_out          (amp_f1_out),
        .peak_result_valid   (peak_result_valid),
        .fft_result_valid    (fft_result_valid),
        .fft_busy            (fft_busy),
        .peak_busy           (peak_busy),
        .hmi_busy            (hmi_busy),
        .waveform_done       (waveform_done),
        .uart_tx             (uart_tx),
        .frame_valid         (frame_valid),
        .uart_state          (uart_state)
    );

    // Generated by scripts/setup_board_top.tcl.  Probe widths match the
    // actual top-level signals, with the redundant MSB of vpp/amp omitted to
    // keep the capture memory compact while retaining their useful ranges.
    ila_system u_ila_system (
        .clk   (clk_algo),
        .probe0(frame_valid),
        .probe1(vpp_out[15:0]),
        .probe2(vrms_out),
        .probe3(amp_f1_out[30:0]),
        .probe4(max_index_out),
        .probe5(uart_state)
    );

endmodule
