`timescale 1ns / 1ps

//==============================================================================
// MMCM_Top
//------------------------------------------------------------------------------
// Basys 3 100 MHz clock input wrapper.
//
// A 7-series MMCM cannot legally generate 4.096 MHz directly: its minimum
// legal output frequency is approximately 4.687 MHz when the VCO and output
// divider limits are considered.  The generated Clocking Wizard instance
// therefore produces:
//
//     clk_out1 = 100 MHz
//     clk_out2 = 12.2881356 MHz (VCO = 725 MHz, divide = 59)
//
// A 7-series BUFR /3 then produces clk_adc = 4.0960452 MHz, an error of about
// 11 ppm from the requested 4.096 MHz.  BUFR is the supported regional clock
// divider on Artix-7 (BUFGCE_DIV is not an Artix-7 primitive).  This clock only
// drives the small ADC capture domain and the forwarded ODDR, so regional
// routing is sufficient.  The wrapper interface intentionally presents the
// final ADC clock as clk_adc so the rest of the design does not need to know
// this implementation detail.
//==============================================================================
module MMCM_Top (
    input  wire sys_clk_in,
    input  wire reset,
    output wire clk_algo,
    output wire clk_adc,
    output wire locked
);

    wire clk_adc_mmcm;

    // Generated by scripts/setup_board_top.tcl.
    mmcm_top_wiz u_mmcm_top_wiz (
        .clk_in1 (sys_clk_in),
        .reset   (reset),
        .locked  (locked),
        .clk_out1(clk_algo),
        .clk_out2(clk_adc_mmcm)
    );

    // BUFR is the Artix-7-supported dedicated clock divider.  CE is held low
    // and CLR asserted until the MMCM has locked, preventing an invalid clock
    // from reaching the ADC or capture logic during startup.
    BUFR #(
        .BUFR_DIVIDE("3"),
        .SIM_DEVICE("7SERIES")
    ) u_adc_clock_bufr (
        .I  (clk_adc_mmcm),
        .CE (locked && !reset),
        .CLR(!locked || reset),
        .O  (clk_adc)
    );

endmodule
